"""因子研究 HTML 报告渲染器。"""

from __future__ import annotations

import html
from pathlib import Path

import pandas as pd

from factorlab.research.report_overview import ReportOverviewBuilder
from factorlab.utils import ensure_within


class ReportRenderer:
    """研究报告渲染器（OOP 接口）。"""

    def __init__(self, out_dir: Path):
        self.out_dir = out_dir

    def _safe_rel(self, path: Path) -> str:
        safe_path = ensure_within(self.out_dir, path)
        rel = safe_path.relative_to(self.out_dir.resolve()).as_posix()
        return html.escape(rel, quote=True)

    def _render_table_links(self, rows: list[str], table_map: dict[str, list[Path]]) -> None:
        rows.append("<ul>")
        for section, tables in table_map.items():
            rows.append(f"<li><strong>{html.escape(str(section))}</strong><ul>")
            for table_path in tables:
                rel = self._safe_rel(table_path)
                rows.append(f"<li><a href='{rel}'>{rel}</a></li>")
            rows.append("</ul></li>")
        rows.append("</ul>")

    def _render_all_figures(self, rows: list[str], figure_map: dict[str, list[Path]]) -> None:
        for section, figs in figure_map.items():
            rows.append(f"<h3>{html.escape(str(section))}</h3>")
            for fig in figs:
                rel = self._safe_rel(fig)
                rows.append(f"<div><img src='{rel}' style='max-width:980px; width:100%;'/></div>")

    def _render_adapter_audit(self, rows: list[str]) -> None:
        audit_dir = self.out_dir / "tables" / "data"
        if not audit_dir.exists():
            return
        audit_files = sorted(audit_dir.glob("*.csv"))
        if not audit_files:
            return
        rows.append("<h2>Data Adapter Audit / 数据适配器审计</h2>")
        rows.append("<ul>")
        for table_path in audit_files:
            rel = self._safe_rel(table_path)
            rows.append(f"<li><a href='{rel}'>{rel}</a></li>")
        rows.append("</ul>")

        summary_path = audit_dir / "adapter_quality_audit.csv"
        if summary_path.exists():
            summary = pd.read_csv(summary_path)
            rows.append("<h3>审计预览</h3>")
            rows.append(summary.to_html(index=False))

    def render(
        self,
        summary: pd.DataFrame,
        figure_map: dict[str, list[Path]],
        table_map: dict[str, list[Path]],
    ) -> Path:
        table_map = {k: list(v) for k, v in table_map.items()}
        table_map.setdefault("global", [])
        overview = ReportOverviewBuilder(self.out_dir).build(
            summary=summary,
            figure_map=figure_map,
            table_map=table_map,
        )

        rows: list[str] = []
        rows.append("<h1>Stock Factor Research Report</h1>")
        rows.append(
            "<p>Generated by FactorLab pipeline. Includes IC, quantiles, turnover, diagnostics and significance.</p>"
        )

        rows.append("<h2>快速开始（30 秒）</h2>")
        rows.append("<ol>")
        rows.append("<li>先看 <a href='README_FIRST.md'>README_FIRST.md</a>（如何解读）</li>")
        rows.append(f"<li>进入 <a href='{self._safe_rel(overview.overview_dir / 'README.md')}'>overview/README.md</a>（一站式入口）</li>")
        if overview.quick_summary_path.exists():
            rows.append(
                f"<li>看 <a href='{self._safe_rel(overview.quick_summary_path)}'>quick_summary.csv</a>（最关键排名）</li>"
            )
        rows.append(
            f"<li>再看 <a href='{self._safe_rel(overview.nav_path)}'>report_navigation.json</a>（程序化导航）</li>"
        )
        rows.append("</ol>")

        if not overview.quick_summary.empty:
            rows.append("<h2>Top 因子速览</h2>")
            rows.append(overview.quick_summary.head(10).to_html(index=False, float_format=lambda x: f"{x:.4f}"))

        if not overview.factor_scorecard.empty:
            rows.append("<h2>核心评分卡（建议优先）</h2>")
            rows.append("<p>仅显示用于决策的核心指标组合，诊断类指标仍保留在明细表中。</p>")
            rows.append(overview.factor_scorecard.head(10).to_html(index=False, float_format=lambda x: f"{x:.4f}"))

        if not overview.factor_insights.empty:
            rows.append("<h2>自动解读模板（可直接读结论）</h2>")
            rows.append(
                overview.factor_insights[
                    ["rank", "factor", "strength", "confidence", "risk", "summary_text", "action_text"]
                ]
                .head(10)
                .to_html(index=False)
            )

        if not overview.metric_inventory.empty:
            rows.append("<h2>指标分层（Core / Diagnostic）</h2>")
            rows.append(overview.metric_inventory.to_html(index=False, float_format=lambda x: f"{x:.4f}"))

        if overview.key_figures:
            rows.append("<h2>关键图（优先看）</h2>")
            for fig in overview.key_figures:
                rel = self._safe_rel(fig)
                rows.append(f"<div><img src='{rel}' style='max-width:980px; width:100%;'/></div>")

        rows.append("<details>")
        rows.append("<summary>查看完整 Summary 表</summary>")
        rows.append(summary.to_html(index=False, float_format=lambda x: f"{x:.4f}"))
        rows.append("</details>")

        rows.append("<details>")
        rows.append("<summary>查看全部图表</summary>")
        self._render_all_figures(rows, figure_map=figure_map)
        rows.append("</details>")

        rows.append("<details>")
        rows.append("<summary>查看全部数据表</summary>")
        self._render_table_links(rows, table_map=table_map)
        rows.append("</details>")

        self._render_adapter_audit(rows)

        html_text = "\n".join(
            [
                "<!doctype html>",
                "<html>",
                "<head><meta charset='utf-8'><title>FactorLab Report</title></head>",
                "<body>",
                *rows,
                "</body></html>",
            ]
        )
        out = self.out_dir / "index.html"
        out.write_text(html_text, encoding="utf-8")
        return out


def render_report(
    out_dir: Path,
    summary: pd.DataFrame,
    figure_map: dict[str, list[Path]],
    table_map: dict[str, list[Path]],
) -> Path:
    """兼容函数式调用，内部委托给 OOP 报告渲染器。"""
    return ReportRenderer(out_dir=out_dir).render(summary=summary, figure_map=figure_map, table_map=table_map)

