"""HTML report renderer for factor research outputs."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def render_report(
    out_dir: Path,
    summary: pd.DataFrame,
    figure_map: dict[str, list[Path]],
    table_map: dict[str, list[Path]],
) -> Path:
    """Generate a lightweight static HTML report with figures and table links."""
    rows = []
    rows.append("<h1>Stock Factor Research Report</h1>")
    rows.append(
        "<p>Generated by FactorLab pipeline. Includes IC, quantiles, turnover, diagnostics and significance.</p>"
    )

    rows.append("<h2>Summary</h2>")
    rows.append(summary.to_html(index=False, float_format=lambda x: f"{x:.4f}"))

    for section, figs in figure_map.items():
        rows.append(f"<h2>{section}</h2>")
        for fig in figs:
            rel = fig.relative_to(out_dir).as_posix()
            rows.append(f"<div><img src='{rel}' style='max-width:980px; width:100%;'/></div>")

    rows.append("<h2>Tables</h2>")
    for section, tables in table_map.items():
        rows.append(f"<h3>{section}</h3>")
        rows.append("<ul>")
        for t in tables:
            rel = t.relative_to(out_dir).as_posix()
            rows.append(f"<li><a href='{rel}'>{rel}</a></li>")
        rows.append("</ul>")

    html = "\n".join(rows)
    out = out_dir / "index.html"
    out.write_text(html, encoding="utf-8")
    return out
