"""因子研究 HTML 报告渲染器。"""

from __future__ import annotations

import html
from pathlib import Path

import pandas as pd

from factorlab.utils import ensure_within


class ReportRenderer:
    """研究报告渲染器（OOP 接口）。"""

    def __init__(self, out_dir: Path):
        self.out_dir = out_dir

    def _safe_rel(self, path: Path) -> str:
        safe_path = ensure_within(self.out_dir, path)
        rel = safe_path.relative_to(self.out_dir.resolve()).as_posix()
        return html.escape(rel, quote=True)

    def _render_tables(self, rows: list[str], table_map: dict[str, list[Path]]) -> None:
        rows.append("<h2>Tables</h2>")
        for section, tables in table_map.items():
            rows.append(f"<h3>{html.escape(str(section))}</h3>")
            rows.append("<ul>")
            for table_path in tables:
                rel = self._safe_rel(table_path)
                rows.append(f"<li><a href='{rel}'>{rel}</a></li>")
            rows.append("</ul>")

    def _render_adapter_audit(self, rows: list[str]) -> None:
        audit_dir = self.out_dir / "tables" / "data"
        if not audit_dir.exists():
            return
        audit_files = sorted(audit_dir.glob("*.csv"))
        if not audit_files:
            return
        rows.append("<h2>Data Adapter Audit</h2>")
        rows.append("<ul>")
        for table_path in audit_files:
            rel = self._safe_rel(table_path)
            rows.append(f"<li><a href='{rel}'>{rel}</a></li>")
        rows.append("</ul>")

        summary_path = audit_dir / "adapter_quality_audit.csv"
        if summary_path.exists():
            summary = pd.read_csv(summary_path)
            rows.append("<h3>Adapter Quality Summary (Preview)</h3>")
            rows.append(summary.to_html(index=False))

    def render(
        self,
        summary: pd.DataFrame,
        figure_map: dict[str, list[Path]],
        table_map: dict[str, list[Path]],
    ) -> Path:
        rows: list[str] = []
        rows.append("<h1>Stock Factor Research Report</h1>")
        rows.append(
            "<p>Generated by FactorLab pipeline. Includes IC, quantiles, turnover, diagnostics and significance.</p>"
        )

        rows.append("<h2>Summary</h2>")
        rows.append(summary.to_html(index=False, float_format=lambda x: f"{x:.4f}"))

        for section, figs in figure_map.items():
            rows.append(f"<h2>{html.escape(str(section))}</h2>")
            for fig in figs:
                rel = self._safe_rel(fig)
                rows.append(f"<div><img src='{rel}' style='max-width:980px; width:100%;'/></div>")

        self._render_tables(rows, table_map=table_map)
        self._render_adapter_audit(rows)

        html_text = "\n".join(
            [
                "<!doctype html>",
                "<html>",
                "<head><meta charset='utf-8'><title>FactorLab Report</title></head>",
                "<body>",
                *rows,
                "</body></html>",
            ]
        )
        out = self.out_dir / "index.html"
        out.write_text(html_text, encoding="utf-8")
        return out


def render_report(
    out_dir: Path,
    summary: pd.DataFrame,
    figure_map: dict[str, list[Path]],
    table_map: dict[str, list[Path]],
) -> Path:
    """兼容函数式调用，内部委托给 OOP 报告渲染器。"""
    return ReportRenderer(out_dir=out_dir).render(summary=summary, figure_map=figure_map, table_map=table_map)
