"""Training utilities for model-based factors and OOF workflows."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from factorlab.config import SyntheticConfig
from factorlab.data.synthetic import generate_synthetic_panel
from factorlab.factors.simple import LiquidityShockFactor, MomentumFactor, VolatilityFactor
from factorlab.models.registry import ModelRegistry
from factorlab.research.forward_returns import add_forward_returns


@dataclass(slots=True)
class OOFSplitConfig:
    """Rolling split settings for OOF model-factor training."""

    train_days: int = 252
    valid_days: int = 21
    step_days: int = 21
    embargo_days: int = 5
    min_train_rows: int = 500
    min_valid_rows: int = 100

    def __post_init__(self) -> None:
        if int(self.train_days) <= 0:
            raise ValueError("OOFSplitConfig.train_days must be > 0.")
        if int(self.valid_days) <= 0:
            raise ValueError("OOFSplitConfig.valid_days must be > 0.")
        if int(self.step_days) <= 0:
            raise ValueError("OOFSplitConfig.step_days must be > 0.")
        if int(self.embargo_days) < 0:
            raise ValueError("OOFSplitConfig.embargo_days must be >= 0.")
        if int(self.min_train_rows) <= 0:
            raise ValueError("OOFSplitConfig.min_train_rows must be > 0.")
        if int(self.min_valid_rows) <= 0:
            raise ValueError("OOFSplitConfig.min_valid_rows must be > 0.")


@dataclass(slots=True)
class OOFModelFactorResult:
    """Artifacts generated by OOF model-factor training."""

    oof_predictions: pd.DataFrame
    fold_summary: pd.DataFrame
    tuning_summary: pd.DataFrame
    final_model: Any
    best_params: dict[str, Any]
    best_score: float


def _daily_rank_ic(df: pd.DataFrame, pred_col: str, label_col: str) -> float:
    rows: list[float] = []
    for _, grp in df.groupby("date"):
        g = grp[[pred_col, label_col]].dropna()
        if len(g) < 5:
            continue
        rows.append(float(g[pred_col].corr(g[label_col], method="spearman")))
    if not rows:
        return float("nan")
    return float(np.nanmean(rows))


def _iter_folds(dates: list[pd.Timestamp], cfg: OOFSplitConfig):
    if int(cfg.step_days) <= 0:
        raise ValueError("OOFSplitConfig.step_days must be > 0.")
    i = int(cfg.train_days) + int(cfg.embargo_days)
    fold_id = 0
    while i + int(cfg.valid_days) <= len(dates):
        train_end = i - int(cfg.embargo_days)
        train_start = max(0, train_end - int(cfg.train_days))
        valid_start = i
        valid_end = i + int(cfg.valid_days)

        train_dates = dates[train_start:train_end]
        valid_dates = dates[valid_start:valid_end]
        if train_dates and valid_dates:
            yield fold_id, train_dates, valid_dates

        fold_id += 1
        i += int(cfg.step_days)


def _normalize_param_grid(param_grid: list[dict[str, object]] | None) -> list[dict[str, object]]:
    if not param_grid:
        return [{}]
    clean = [dict(p) for p in param_grid if isinstance(p, dict)]
    return clean if clean else [{}]


def _fit_predict_fold(
    df: pd.DataFrame,
    feature_cols: list[str],
    label_col: str,
    model_name: str,
    params: dict[str, object],
    train_dates: list[pd.Timestamp],
    valid_dates: list[pd.Timestamp],
    cfg: OOFSplitConfig,
) -> tuple[pd.DataFrame, dict[str, float | int | str] | None]:
    train = df[df["date"].isin(train_dates)].copy()
    valid = df[df["date"].isin(valid_dates)].copy()

    train = train.dropna(subset=[*feature_cols, label_col]).copy()
    valid = valid.dropna(subset=feature_cols).copy()
    if len(train) < int(cfg.min_train_rows) or len(valid) < int(cfg.min_valid_rows):
        return pd.DataFrame(), None

    model = ModelRegistry.create(model_name, params=params)
    x_train = train[feature_cols].astype(float).fillna(0.0)
    y_train = train[label_col].astype(float)
    model.fit(x_train, y_train)

    x_valid = valid[feature_cols].astype(float).fillna(0.0)
    pred = model.predict(x_valid)

    scored = valid[["date", "asset", label_col]].copy()
    scored["pred"] = pred.astype(float)
    fold_rank_ic = _daily_rank_ic(scored, pred_col="pred", label_col=label_col)
    fold_info: dict[str, float | int | str] = {
        "train_rows": int(len(train)),
        "valid_rows": int(len(valid)),
        "oof_rank_ic": fold_rank_ic,
    }
    return scored, fold_info


def train_oof_model_factor(
    panel: pd.DataFrame,
    feature_cols: list[str],
    model_name: str = "ridge",
    label_horizon: int = 5,
    split_config: OOFSplitConfig | None = None,
    param_grid: list[dict[str, object]] | None = None,
) -> OOFModelFactorResult:
    """Train an OOF model factor via rolling time splits."""
    cfg = split_config or OOFSplitConfig()
    missing = [c for c in ["date", "asset", "close", *feature_cols] if c not in panel.columns]
    if missing:
        raise KeyError(f"Panel missing required columns for OOF training: {missing}")

    df = panel.copy()
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df["asset"] = df["asset"].astype(str)
    df = df.dropna(subset=["date", "asset"]).sort_values(["date", "asset"]).reset_index(drop=True)
    df = add_forward_returns(df, horizons=[int(label_horizon)], price_col="close")
    label_col = f"fwd_ret_{int(label_horizon)}"

    unique_dates = sorted(pd.to_datetime(df["date"].dropna().unique()))
    if len(unique_dates) < (int(cfg.train_days) + int(cfg.valid_days) + int(cfg.embargo_days) + 5):
        raise RuntimeError("Not enough unique dates for OOF split configuration.")

    candidates = _normalize_param_grid(param_grid)
    tuning_rows: list[dict[str, object]] = []

    best_params: dict[str, object] = {}
    best_score = -np.inf
    for idx, params in enumerate(candidates):
        fold_scores: list[float] = []
        fold_count = 0
        for _, train_dates, valid_dates in _iter_folds(unique_dates, cfg=cfg):
            scored, fold_info = _fit_predict_fold(
                df=df,
                feature_cols=feature_cols,
                label_col=label_col,
                model_name=model_name,
                params=params,
                train_dates=train_dates,
                valid_dates=valid_dates,
                cfg=cfg,
            )
            if scored.empty or fold_info is None:
                continue
            fold_count += 1
            fold_scores.append(float(fold_info["oof_rank_ic"]))

        mean_score = float(np.nanmean(fold_scores)) if fold_scores else float("nan")
        tuning_rows.append(
            {
                "param_id": idx,
                "params_json": json.dumps(params, ensure_ascii=False, default=str),
                "mean_oof_rank_ic": mean_score,
                "valid_folds": fold_count,
            }
        )
        if np.isfinite(mean_score) and mean_score > best_score:
            best_score = mean_score
            best_params = dict(params)

    if not np.isfinite(best_score):
        raise RuntimeError("OOF tuning failed: no valid folds produced finite rank-IC.")

    oof_parts: list[pd.DataFrame] = []
    fold_rows: list[dict[str, object]] = []
    for fold_id, train_dates, valid_dates in _iter_folds(unique_dates, cfg=cfg):
        scored, fold_info = _fit_predict_fold(
            df=df,
            feature_cols=feature_cols,
            label_col=label_col,
            model_name=model_name,
            params=best_params,
            train_dates=train_dates,
            valid_dates=valid_dates,
            cfg=cfg,
        )
        if scored.empty or fold_info is None:
            continue
        scored["fold_id"] = int(fold_id)
        scored["model"] = str(model_name)
        oof_parts.append(scored.rename(columns={label_col: "label"}))
        fold_rows.append(
            {
                "fold_id": int(fold_id),
                "train_start": pd.Timestamp(min(train_dates)),
                "train_end": pd.Timestamp(max(train_dates)),
                "valid_start": pd.Timestamp(min(valid_dates)),
                "valid_end": pd.Timestamp(max(valid_dates)),
                **fold_info,
            }
        )

    if not oof_parts:
        raise RuntimeError("OOF training produced no predictions. Check split sizes and data coverage.")

    oof_predictions = pd.concat(oof_parts, ignore_index=True).sort_values(
        ["date", "asset", "fold_id"]
    ).reset_index(drop=True)
    fold_summary = pd.DataFrame(fold_rows).sort_values("fold_id").reset_index(drop=True)
    tuning_summary = pd.DataFrame(tuning_rows).sort_values("param_id").reset_index(drop=True)

    train_all = df.dropna(subset=[*feature_cols, label_col]).copy()
    if train_all.empty:
        raise RuntimeError("No rows available to fit final model after OOF training.")
    final_model = ModelRegistry.create(model_name, params=best_params)
    final_model.fit(train_all[feature_cols].astype(float).fillna(0.0), train_all[label_col].astype(float))

    return OOFModelFactorResult(
        oof_predictions=oof_predictions,
        fold_summary=fold_summary,
        tuning_summary=tuning_summary,
        final_model=final_model,
        best_params=best_params,
        best_score=float(best_score),
    )


def train_model_factor(
    model_name: str = "ridge",
    model_out: str = "artifacts/models/model_factor.joblib",
    synthetic_config: SyntheticConfig | None = None,
) -> Path:
    """Train and persist a simple predictive model for factor inference."""
    cfg = synthetic_config or SyntheticConfig(n_assets=30, n_days=260, seed=17)
    panel = generate_synthetic_panel(cfg)

    factors = [
        MomentumFactor(name="momentum_20", lookback=20),
        VolatilityFactor(name="volatility_20", window=20),
        LiquidityShockFactor(name="liquidity_shock", window=20),
    ]
    for fac in factors:
        panel[fac.name] = fac.compute(panel)

    panel = add_forward_returns(panel, horizons=[5])
    panel = panel.dropna(subset=["momentum_20", "volatility_20", "liquidity_shock", "fwd_ret_5"])

    train = panel.sort_values("date").copy()
    split = int(len(train) * 0.8)
    x_train = train[["momentum_20", "volatility_20", "liquidity_shock"]].iloc[:split].astype(float)
    y_train = train["fwd_ret_5"].iloc[:split].astype(float)

    model = ModelRegistry.create(model_name)
    model.fit(x_train, y_train)

    out = Path(model_out)
    metadata = {
        "feature_cols": ["momentum_20", "volatility_20", "liquidity_shock"],
        "label_col": "fwd_ret_5",
    }
    return ModelRegistry.save(model, out, model_name=model_name, metadata=metadata)
